import json
import os
import pathlib
import shutil
import subprocess
import pytest

from tests.js_source import static_js_files

REPO_ROOT = pathlib.Path(__file__).parent.parent


def _eslint_targets():
    """Repo-relative paths of every non-vendor static JS file, for the linters."""
    return sorted(
        path.relative_to(REPO_ROOT).as_posix()
        for path in static_js_files()
    )


@pytest.mark.unit
def test_code_quality_pylint():
    """Verify that there are no unused imports, unused variables, or redefined built-ins.

    This targets both the core implementation files and the test files.
    """
    target_paths = [
        "services/systemd_manager.py",
        "scripts/script_ssh.py",
        "services/sync_engine.py",
        "api/routes.py",
        "scripts/import_servers.py",
        "tests/",
    ]
    
    # Run pylint with only our targeted rules enabled
    cmd = [
        "pylint", 
        "--disable=all", 
        "--enable=unused-import,unused-variable,redefined-builtin"
    ] + target_paths
    
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True
    )
    
    assert result.returncode == 0, (
        f"Pylint detected code quality issues:\n{result.stdout}"
    )


@pytest.mark.unit
def test_eslint_static_files():
    """Verify that ESLint runs successfully on the static JavaScript files using the codacy config."""
    config_path = ".codacy/tools-configs/eslint.config.mjs"
    if not os.path.exists(config_path):
        pytest.skip(f"{config_path} not found (generated by the Codacy CLI)")
    cmd = [
        "npx",
        "eslint",
        "--config",
        config_path,
    ] + _eslint_targets()
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True
    )
    assert result.returncode == 0, (
        f"ESLint detected code quality issues:\n{result.stdout}\n{result.stderr}"
    )


@pytest.mark.unit
def test_no_eslint_object_injection():
    """Verify that there are no ESLint object-injection warnings in static JS files."""
    cli_path = shutil.which("codacy-analysis")
    if not cli_path:
        fallback = os.path.expanduser("~/.npm-global/bin/codacy-analysis")
        if os.path.exists(fallback):
            cli_path = fallback
        else:
            pytest.skip("codacy-analysis not found in PATH or ~/.npm-global/bin/")
    output_file = "test_results.json"
    all_issues = []
    for target in _eslint_targets():
        if os.path.exists(output_file):
            os.remove(output_file)
        cmd = [
            cli_path,
            "analyze",
            target,
            "--output-format",
            "json",
            "--output",
            output_file
        ]
        subprocess.run(
            cmd,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL
        )
        assert os.path.exists(output_file), f"Analysis output file was not created for {target}."
        with open(output_file, "r") as f:
            data = json.load(f)
        issues = data.get("issues", [])
        object_injection_issues = [
            issue for issue in issues
            if issue.get("patternId") == "ESLint9_security_detect-object-injection"
        ]
        all_issues.extend(object_injection_issues)

    if os.path.exists(output_file):
        os.remove(output_file)

    assert len(all_issues) == 0, (
        f"Detected {len(all_issues)} ESLint object-injection warnings in static files:\n"
        f"{json.dumps(all_issues, indent=2)}"
    )

