"""The static JS modules must not carry imports nothing in the file uses.

Issue #174 splits static/main.js one cluster per pull request. A name that one
extraction legitimately imports goes stale when the next one moves its last call
site into a module, and that happened three times running: #430 left
`refreshSessionsStripVisibility` and the `Terminal` eslint global behind, #432
left `chartColorByName` and `refreshChartSwatches`. Each was caught only after
merge by an external analyzer, because the eslint gate that would flag it needs a
config generated by the Codacy CLI that is not in this repo.

This asserts the same property with nothing but the source text, so it runs
locally and in CI like any other unit test.
"""
import pathlib
import re

import pytest

from tests.js_source import static_js_files

REPO_ROOT = pathlib.Path(__file__).parent.parent


IMPORT_BLOCK_RE = re.compile(
    r"import\s*\{([^}]*)\}\s*from\s*['\"][^'\"]+['\"]\s*;?",
    re.MULTILINE,
)


def _imported_names(block_body):
    """Local names bound by one `import { ... }` clause, resolving `as` aliases."""
    names = []
    for part in block_body.split(","):
        part = part.strip()
        if not part:
            continue
        # `foo as bar` binds `bar`; a bare `foo` binds itself.
        names.append(part.split(" as ")[-1].strip() if " as " in part else part)
    return names


@pytest.mark.unit
def test_no_unused_named_imports_in_static_js():
    """Every name a static JS module imports must be used somewhere in that file.

    The #174 module split moves one cluster per PR, and a name that was
    legitimately imported by one extraction goes stale when the next one takes
    its last call site away. That happened three times in a row (#430 left
    `refreshSessionsStripVisibility` and `Terminal`, #432 left `chartColorByName`
    and `refreshChartSwatches`), and each was caught only after merge, because
    the eslint gate that would flag it needs a config generated by the Codacy
    CLI that is not in the repo. This asserts it locally instead.

    The window bridge counts as a use: a name listed in `Object.assign(window,
    { ... })` is genuinely referenced, even if nothing else in the file calls it.
    """
    offenders = []
    for path in static_js_files():
        content = path.read_text(encoding="utf-8")

        # The body is everything that is not an import statement, so a name
        # appearing only in its own import does not count as using itself.
        body = IMPORT_BLOCK_RE.sub("", content)

        for match in IMPORT_BLOCK_RE.finditer(content):
            for name in _imported_names(match.group(1)):
                if not re.search(rf"\b{re.escape(name)}\b", body):
                    offenders.append(f"{path.relative_to(REPO_ROOT).as_posix()}: {name}")

    assert not offenders, (
        "Unused named imports in static JS (remove them, or the module that "
        "took over the last call site should own them):\n  "
        + "\n  ".join(offenders)
    )
